routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['get.menu']], function () {
    Auth::routes();
    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/', 'UsersController@index');
        Route::resource('users', 'UsersController')->except(['create', 'store']);
        Route::get('/user/configs', 'UsersController@configView');
        Route::post('/user/configs', 'UsersController@configStore');
        Route::resource('artists', 'ArtistsController');
        Route::resource('musics', 'MusicsController');
        Route::resource('plans', 'PlansController');
        Route::resource('payments', 'PaymentsController');
        Route::resource('comments', 'CommentsController');
        Route::post('upload', 'UploadController@index')->name('upload');


        Route::get('/clear-cache', function () {
            return Artisan::call('optimize:clear');
        });
    });
});

app/Models/Musics.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Facades\Auth;

class Musics extends Model
{

    use HasFactory;

    protected $table = 'musics';
    protected $guarded = [];

    /**
     * Get the Artist that owns the Music.
     */
    public function artist()
    {
        return $this->belongsTo(Artists::class, 'artist_id');
    }

    public function like()
    {
        return $this->hasOne(Likes::class, 'music_id');
    }
    public function isLiked()
    {
        return $this->like()->where('user_id',  Auth::id())->exists();
    }

    public function purchase()
    {
        return $this->hasOne(Purchases::class, 'music_id');
    }
    public function isPurchased()
    {
        return $this->purchase()->where('user_id',  Auth::id())->exists();
    }
}

app/Http/Controllers/Api/MusicsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\CommentResource;
use App\Http\Resources\SuccessResource;
use App\Http\Resources\ErrorResource;
use App\Http\Resources\MusicResource;
use App\Http\Resources\SearchResource;
use App\Models\Artists;
use App\Models\Comments;
use App\Models\Musics;
use App\Models\Likes;
use App\Models\Purchases;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class MusicsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $req)
    {

        $cat = $req->cat;
        $items = Musics::with(['artist', 'like']);

        if ($cat == 'popular')
            $items = $items->orderBy('like_count', 'desc');
        else if ($cat == 'recent')
            $items = $items->orderBy('created_at', 'desc');
        else if ($cat == 'premium')
            $items = $items->orderBy('like_count', 'desc')->where('price', '!=', 0);
        else if ($cat == 'free')
            $items = $items->orderBy('like_count', 'desc')->where('price', 0);


        return MusicResource::collection($items->paginate(20));
    }


    public function like($id)
    {
        $user_id = Auth::id();
        $item = Musics::find($id);
        if (!$item) {
            $res         = new \stdClass();
            $res->errors = "Not Found !!";
            return (new ErrorResource($res))
                ->response()
                ->setStatusCode(404);
        }

        $i = Likes::firstOrCreate(['music_id'  => $id, 'user_id' => $user_id]);

        if ($i->wasRecentlyCreated) {
            $item->increment('like_count');
            $item->save();
        }

        return new SuccessResource('liked !!');
    }


    public function unLike($id)
    {
        $user_id = Auth::id();
        $item = Musics::find($id);
        if (!$item) {
            $res         = new \stdClass();
            $res->errors = "Not Found !!";
            return (new ErrorResource($res))
                ->response()
                ->setStatusCode(404);
        }

        $i = Likes::firstWhere(['music_id'  => $id, 'user_id' => $user_id]);
        if (!$i) {
            return new SuccessResource('liked not found !!');
        }

        Likes::destroy($i->id);
        $item->decrement('like_count');
        $item->save();
        return new SuccessResource('UnLiked !!');
    }

    public function search(Request $req)
    {
        $q = $req->q;
        $music = Musics::where('title', 'like', "%{$q}%")->paginate(20);
        $artist = Artists::where('name', 'like', "%{$q}%")->paginate(20);

        return new SearchResource(['music' => $music, 'artist' => $artist]);
    }

    public function getComments($id)
    {
        $items = Comments::with('user')->where('music_id', $id)->orderBy('created_at')->paginate(20);
        return CommentResource::collection($items);
    }

    public function addComment(Request $req, $id)
    {
        $req->validate([
            'text' => 'required|string|min:1|max:10000'
        ]);

        $user_id = Auth::id();
        Comments::create(['music_id'  => $id, 'user_id' => $user_id, 'text' => $req->text]);

        return new SuccessResource('Created !!');
    }

    public function purchaseMusic($id)
    {
        $m = Musics::find($id);
        $user = Auth::user();
        $price = $m->price;

        if ($user->coins < $price) {
            return (new ErrorResource('You have not Enough coins.'))
                ->response()
                ->setStatusCode(404);
        }

        $a = Purchases::firstOrCreate(['user_id' => $user->id, 'music_id' => $m->id]);
        if ($a->wasRecentlyCreated) {
            $user->decrement('coins', $price);
            $user->save();
        }

        return new SuccessResource('Purchased Successfully !!');
    }
}

app/Http/Controllers/MusicsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use App\Models\Artists;
use App\Models\Musics;


class MusicsController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Musics::with('artist')->orderBy('created_at', 'desc')->paginate(20);
        return view('dashboard.musics.list', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $artists = Artists::all();
        return view('dashboard.musics.create', compact('artists'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $req
     * @return \Illuminate\Http\Response
     */
    public function store(Request $req)
    {

        Validator::make($req->all(), [
            'title'             => 'required|min:1|max:64',
            'artist_id'         => 'required',
            'cover'           => 'required',
            'kCover'             => 'required',
            'url'           => 'required',
            'kUrl'           => 'required',
            'price'           => 'required',
        ], [
            'cover.required' => 'The Original Song Cover field is required.',
            'kCover.required' => 'The Karaoke Cover field is required.',
            'url.required' => 'The Song field is required.',
            'kUrl.required' => 'The Karaoke field is required.',
        ])->validate();


        $fields = $req->all(['title', 'artist_id', 'cover', 'kCover', 'url', 'kUrl', 'price']);
        Musics::create($fields);

        $req->session()->flash('message', 'Successfully created');
        return redirect()->route('musics.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Musics::find($id);
        $artists = Artists::all();
        return view('dashboard.musics.edit', compact('item', 'artists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $req
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        Validator::make($req->all(), [
            'title'             => 'required|min:1|max:64',
            'artist_id'         => 'required',
            'cover'           => 'required',
            'kCover'             => 'required',
            'url'           => 'required',
            'kUrl'           => 'required',
            'price'           => 'required',
        ], [
            'cover.required' => 'The Original Song Cover field is required.',
            'kCover.required' => 'The Karaoke Cover field is required.',
            'url.required' => 'The Song field is required.',
            'kUrl.required' => 'The Karaoke field is required.',
        ])->validate();


        $fields = $req->all(['title', 'artist_id', 'cover', 'kCover', 'url', 'kUrl', 'price']);
        $item = Musics::find($id);
        $item->update($fields);
        $req->session()->flash('message', 'Edited Successfully');
        return redirect()->route('musics.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Musics::find($id);
        if ($item) {
            $item->delete();
        }
        return redirect()->route('musics.index');
    }
}

resources/views/dashboard/musics/create.blade.php
@extends('dashboard.base')

@section('css')
<link rel="stylesheet" type="text/css" href="{{asset('css/dropzone.min.css')}}">
@endsection


@section('content')

<div class="container-fluid">
  <div class="animated fadeIn">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-10 col-lg-12 col-xl-12">
        @if(Session::has('message'))
        <div class="alert alert-success" role="alert">{{ Session::get('message') }}</div>
        @endif
        @if ($errors->any())
        <div class="alert alert-danger">
          <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
        @endif
        <div class="card">
          <div class="card-header">
            <h4>Add Music</h4>
          </div>
          <div class="card-body">

            <form method="POST" action="{{ route('musics.store') }}" id="main">
              @csrf

              <div class="form-group row">
                <div class="col-4">
                  <label>Title</label>
                  <input class="form-control" type="text" placeholder="Title" name="title" value="{{ old('title') }}" required autofocus>
                </div>
                <div class="col-4">
                  <label>Artist</label>
                  <select class="form-control" name="artist_id" value="{{ old('artist_id') }}">
                    @foreach($artists as $i)
                    <option value="{{ $i->id }}">{{ $i->name }}</option>
                    @endforeach
                  </select>
                </div>
                <div class="col-4">
                  <label>Price</label>
                  <input class="form-control" type="number" min="0" name="price" required value="{{ old('price') }}">
                </div>
              </div>

              <div class="form-group row">
                <div class="col-6">
                  <label>Original Song</label>
                  <div class="dropzone needsclick" id="url"></div>
                </div>
                <div class="col-6">
                  <label>Cover</label>
                  <div class="dropzone needsclick" id="cover"></div>
                </div>

              </div>

              <div class="form-group row">
                <div class="col-6">
                  <label>Karaoke Song</label>
                  <div class="dropzone needsclick" id="k-url"></div>
                </div>
                <div class="col-6">
                  <label>Cover</label>
                  <div class="dropzone needsclick" id="k-cover"></div>
                </div>
              </div>


              <div class="d-flex justify-content-around">
                <a href="{{ route('musics.index') }}" class="btn btn-primary col-3">Return</a>
                <button class="btn btn-success col-3" type="submit">Add</button>
              </div>

              <input type="hidden" name="cover" value="{{ old('cover') }}">
              <input type="hidden" name="kCover" value="{{ old('kCover') }}">
              <input type="hidden" name="url" value="{{ old('url') }}">
              <input type="hidden" name="kUrl" value="{{ old('kUrl') }}">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('javascript')

<script src="{{asset('js/dropzone.min.js')}}" type="text/javascript"></script>
<script>
  // Dropzone.autoDiscover = false;
  function editForm(name, val) {
    var inp = document.querySelector('form#main > input[name="' + name + '"]')
    if (inp)
      inp.setAttribute("value", val);
  }

  var configs = {
    url: "{{ route('upload') }}",
    maxFilesize: 1,
    acceptedFiles: "image/*",
    addRemoveLinks: false,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    maxFiles: 1,
    init: function() {
      this.on("maxfilesexceeded", function(file) {
        this.removeAllFiles();
        this.addFile(file);
      });
    },
    error: function(file, response) {
      console.log('err =>', response);
      return false;
    }
  }

  Dropzone.options.url = {
    ...configs,
    maxFilesize: 50,
    acceptedFiles: "video/*",
    success: function(file, res) {
      editForm('url', res.success);
    },
  }
  Dropzone.options.kUrl = {
    ...configs,
    maxFilesize: 50,
    acceptedFiles: "video/*",
    success: function(file, res) {
      editForm('kUrl', res.success);
    },
  }

  Dropzone.options.cover = {
    ...configs,
    success: function(file, res) {
      editForm('cover', res.success);
    },
  }

  Dropzone.options.kCover = {
    ...configs,
    success: function(file, res) {
      editForm('kCover', res.success);
    },
  }
</script>
@endsection

resources/views/dashboard/musics/edit.blade.php
@extends('dashboard.base')

@section('css')
<link rel="stylesheet" type="text/css" href="{{asset('css/dropzone.min.css')}}">
@endsection


@section('content')

<div class="container-fluid">
  <div class="animated fadeIn">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-10 col-lg-12 col-xl-12">
        @if(Session::has('message'))
        <div class="alert alert-success" role="alert">{{ Session::get('message') }}</div>
        @endif
        @if ($errors->any())
        <div class="alert alert-danger">
          <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
        @endif
        <div class="card">
          <div class="card-header">
            <h4>Edit: {{ $item->title }}</h4>
          </div>
          <div class="card-body">
            <form method="POST" action="{{ url('musics/'.$item->id) }}" id="main">
              @csrf
              @method('PUT')
              <div class="form-group row">
                <div class="col-4">
                  <label>Title</label>
                  <input class="form-control" type="text" placeholder="Title" name="title" value="{{ $item->title }}" required autofocus>
                </div>
                <div class="col-4">
                  <label>Artist</label>
                  <select class="form-control" name="artist_id" value="{{ $item->artist_id }}">
                    @foreach($artists as $i)
                    <option value="{{ $i->id }}">{{ $i->name }}</option>
                    @endforeach
                  </select>
                </div>
                <div class="col-4">
                  <label>Price</label>
                  <input class="form-control" type="number" min="0" name="price" required value="{{ $item->price }}">
                </div>
              </div>

              <div class="form-group row">
                <div class="col-6">
                  <label>Original Song</label>
                  <div class="dropzone needsclick" id="url"></div>
                  <small class="text-danger my-2 font-weight-bold">if no changes Leave it blank</small>
                </div>
                <div class="col-6">
                  <label>Cover</label>
                  <div class="dropzone needsclick" id="cover"></div>
                  <small class="text-danger my-2 font-weight-bold">if no changes Leave it blank</small>
                </div>

              </div>

              <div class="form-group row">
                <div class="col-6">
                  <label>Karaoke Song</label>
                  <div class="dropzone needsclick" id="k-url"></div>
                  <small class="text-danger my-2 font-weight-bold">if no changes Leave it blank</small>
                </div>
                <div class="col-6">
                  <label>Cover</label>
                  <div class="dropzone needsclick" id="k-cover"></div>
                  <small class="text-danger my-2 font-weight-bold">if no changes Leave it blank</small>
                </div>
              </div>


              <div class="d-flex justify-content-around">
                <a href="{{ route('musics.index') }}" class="btn btn-primary col-3">Return</a>
                <button class="btn btn-success col-3" type="submit">Save</button>
              </div>

              <input type="hidden" name="cover" value="{{ $item->cover }}">
              <input type="hidden" name="kCover" value="{{ $item->kCover }}">
              <input type="hidden" name="url" value="{{ $item->url }}">
              <input type="hidden" name="kUrl" value="{{ $item->kUrl }}">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('javascript')

<script src="{{asset('js/dropzone.min.js')}}" type="text/javascript"></script>
<script>
  // Dropzone.autoDiscover = false;
  function editForm(name, val) {
    var inp = document.querySelector('form#main > input[name="' + name + '"]')
    if (inp)
      inp.setAttribute("value", val);
  }

  var configs = {
    url: "{{ route('upload') }}",
    maxFilesize: 1,
    acceptedFiles: "image/*",
    addRemoveLinks: false,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    maxFiles: 1,
    init: function() {
      this.on("maxfilesexceeded", function(file) {
        this.removeAllFiles();
        this.addFile(file);
      });
    },
    error: function(file, response) {
      console.log('err =>', response);
      return false;
    }
  }

  Dropzone.options.url = {
    ...configs,
    maxFilesize: 50,
    acceptedFiles: "video/*",
    success: function(file, res) {
      editForm('url', res.success);
    },
  }
  Dropzone.options.kUrl = {
    ...configs,
    maxFilesize: 50,
    acceptedFiles: "video/*",
    success: function(file, res) {
      editForm('kUrl', res.success);
    },
  }

  Dropzone.options.cover = {
    ...configs,
    success: function(file, res) {
      editForm('cover', res.success);
    },
  }

  Dropzone.options.kCover = {
    ...configs,
    success: function(file, res) {
      editForm('kCover', res.success);
    },
  }
</script>
@endsection

resources/views/dashboard/musics/list.blade.php
@extends('dashboard.base')

@section('content')

<div class="container-fluid">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
        <div class="card">
          <div class="card-header d-flex align-items-center justify-content-between">
            <h4>Music</h4>
            <a href="{{ route('musics.create') }}" class="btn btn-primary">Add</a>
          </div>
          <div class="card-body">
            <table class="table table-responsive-sm table-striped">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Artist</th>
                  <th class="text-center">Cover</th>
                  <th class="text-center">Karaoke Cover</th>
                  <th class="text-center">Premium</th>
                  <th class="text-center">Price</th>
                  <th class="text-center"># Likes</th>
                  <th class="text-center">Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach($items as $i)
                <tr>
                  <td>
                    <strong>{{ $i->title }}</strong>
                  </td>
                  <td>{{ $i->artist->name }}</td>
                  <td class="text-center" style="height: 85px;">
                    <img src={{ asset("public/"."{$i->cover}") }} height="60" alt="Cover" />
                  </td>
                  <td class="text-center" style="height: 85px;">
                    <img src={{ asset("public/"."{$i->kCover}") }} height="60" alt="Cover" />
                  </td>
                  <td class="text-center">
                    @if($i->price)
                    <i class="text-success h3 cil-check-circle"></i>
                    @endif
                  </td>
                  <td class="text-center">
                    @if($i->price)
                    {{ $i->price }}
                    @else
                    <strong>free</strong>
                    @endif
                  </td>
                  <td class="text-center">{{ $i->like_count }}</td>
                  <td>
                    <div class="d-flex align-items-center justify-content-around">
                      <!-- <a href="{{ url('/musics/' . $i->id) }}" class="btn btn-outline-primary" data-toggle="tooltip" title="View"><i class="cil-magnifying-glass"></i></a> -->
                      <a href="{{ url('/musics/' . $i->id . '/edit') }}" class="btn btn-outline-warning" data-toggle="tooltip" title="Edit"><i class="cil-pencil"></i></a>
                      <form action="{{ route('musics.destroy', $i->id ) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-outline-danger" data-toggle="tooltip" title="Delete"><i class="cil-trash"></i></button>
                      </form>
                    </div>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
            {{ $items->links() }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection


@section('javascript')

@endsection