routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['get.menu']], function () {
    Auth::routes();
    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/', 'UsersController@index');
        Route::resource('users', 'UsersController')->except(['create', 'store']);
        Route::get('/user/configs', 'UsersController@configView');
        Route::post('/user/configs', 'UsersController@configStore');
        Route::resource('artists', 'ArtistsController');
        Route::resource('musics', 'MusicsController');
        Route::resource('plans', 'PlansController');
        Route::resource('payments', 'PaymentsController');
        Route::resource('comments', 'CommentsController');
        Route::post('upload', 'UploadController@index')->name('upload');


        Route::get('/clear-cache', function () {
            return Artisan::call('optimize:clear');
        });
    });
});

app/Models/Artists.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Facades\Auth;

class Artists extends Model
{

    use HasFactory;

    protected $table = 'artists';

    public function music()
    {
        return $this->hasMany(Musics::class, "artist_id");
    }
    public function follow()
    {
        return $this->hasOne(Follows::class, 'artist_id');
    }

    public function isFollowed()
    {
        return $this->follow()->where('user_id',  Auth::id())->exists();
    }
}

app/Http/Controllers/Api/ArtistsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\SuccessResource;
use App\Http\Resources\ErrorResource;
use App\Http\Resources\ArtistWithMusicResource;
use App\Http\Resources\MusicResource;
use App\Models\Artists;
use App\Models\Follows;
use App\Models\Musics;
use Illuminate\Support\Facades\Auth;

class ArtistsController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Artists::withCount('music')->paginate(20);
        return ArtistWithMusicResource::collection($items);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function follow($id)
    {
        $user_id = Auth::id();
        $item = Artists::find($id);
        if (!$item) {
            $res         = new \stdClass();
            $res->errors = "Not Found !!";
            return (new ErrorResource($res))
                ->response()
                ->setStatusCode(404);
        }

        $i = Follows::firstOrCreate(['artist_id'  => $id, 'user_id' => $user_id]);
        if ($i->wasRecentlyCreated) {
            $item->increment('follow_count');
            $item->save();
        }
        return new SuccessResource('followed');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function unFollow($id)
    {
        $user_id = Auth::id();
        $item = Artists::find($id);
        if (!$item) {
            $res         = new \stdClass();
            $res->errors = "Not Found !!";
            return (new ErrorResource($res))
                ->response()
                ->setStatusCode(404);
        }

        $i = Follows::firstWhere(['artist_id'  => $id, 'user_id' => $user_id]);
        if ($i) {
            Follows::destroy($i->id);
            $item->decrement('follow_count');
            $item->save();
        }
        return new SuccessResource('UnFollowed !!');
    }

    public function getMusics($id)
    {
        $items = Musics::where('artist_id', $id)->paginate(20);
        return MusicResource::collection($items);
    }
}

app/Http/Controllers/ArtistsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Artists;

class ArtistsController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Artists::withCount('music')->orderBy('created_at', 'desc')->paginate(20);
        return view('dashboard.artists.list', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.artists.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $req
     * @return \Illuminate\Http\Response
     */
    public function store(Request $req)
    {
        $v = $req->validate([
            'name'             => 'required|min:1|max:64',
            'cover'           => 'required',
        ]);

        $item = new Artists();
        $item->name     = $req->input('name');
        $item->cover   = $req->input('cover');
        $item->save();
        $req->session()->flash('message', 'Successfully created');
        return redirect()->route('artists.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Artists::find($id);
        return view('dashboard.artists.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $req
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        $v = $req->validate([
            'name'             => 'required|min:1|max:64',
            'cover'           => 'required',
        ]);

        $item = Artists::find($id);
        $item->name     = $req->input('name');
        $item->cover   = $req->input('cover');
        $item->save();
        $req->session()->flash('message', 'Edited Successfully');
        return redirect()->route('artists.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Artists::find($id);
        if ($item) {
            $item->delete();
        }
        return redirect()->route('artists.index');
    }
}

resources/views/dashboard/artists/create.blade.php
@extends('dashboard.base')

@section('css')
<link rel="stylesheet" type="text/css" href="{{asset('css/dropzone.min.css')}}">
@endsection

@section('content')

<div class="container-fluid">
  <div class="animated fadeIn">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-10 col-lg-8 col-xl-8">
        <div class="card">
          <div class="card-header">
            <h4>Add Artist</h4>
          </div>
          <div class="card-body">
            <form method="POST" action="{{ route('artists.store') }}" id="main">
              @csrf
              <div class="form-group">
                <label>Name</label>
                <input class="form-control" type="text" placeholder="Name" name="name" value="{{ old('name') }}" required autofocus>
              </div>

              <div class="form-group">
                <label>Cover</label>
                <div class="dropzone needsclick" id="cover"></div>
              </div>

              <div class="d-flex justify-content-around">
                <a href="{{ route('artists.index') }}" class="btn btn-primary col-4">Return</a>
                <button class="btn btn-success col-4" type="submit">Add</button>
              </div>

              <input type="hidden" name="cover" value="{{ old('cover') }}">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('javascript')

<script src="{{asset('js/dropzone.min.js')}}" type="text/javascript"></script>
<script>
  // Dropzone.autoDiscover = false;
  function editForm(name, val) {
    var inp = document.querySelector('form#main > input[name="' + name + '"]')
    if (inp)
      inp.setAttribute("value", val);
  }

  var configs = {
    url: "{{ route('upload') }}",
    maxFilesize: 1,
    acceptedFiles: "image/*",
    addRemoveLinks: false,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    maxFiles: 1,
    init: function() {
      this.on("maxfilesexceeded", function(file) {
        this.removeAllFiles();
        this.addFile(file);
      });
    },
    error: function(file, response) {
      console.log('err =>', response);
      return false;
    }
  }

  Dropzone.options.cover = {
    ...configs,
    success: function(file, res) {
      editForm('cover', res.success);
    },
  }
</script>
@endsection

resources/views/dashboard/artists/edit.blade.php
@extends('dashboard.base')

@section('css')
<link rel="stylesheet" type="text/css" href="{{asset('css/dropzone.min.css')}}">
@endsection

@section('content')

<div class="container-fluid">
  <div class="animated fadeIn">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-10 col-lg-8 col-xl-8">
        <div class="card">
          <div class="card-header">
            <h4>Edit: {{ $item->name }}</h4>
          </div>
          <div class="card-body">
            <form method="POST" action="{{ url('artists/'.$item->id) }}" id="main">
              @csrf
              @method('PUT')
              <div class="form-group">
                <label>Name</label>
                <input class="form-control" type="text" placeholder="Name" name="name" value="{{ $item->name }}" required autofocus>
              </div>
              <div class="form-group">
                <label>Cover</label>
                <div class="dropzone needsclick" id="cover"></div>
                <small class="text-danger my-2 font-weight-bold">if no changes Leave it blank</small>
              </div>

              <div class="d-flex justify-content-around">
                <a href="{{ route('artists.index') }}" class="btn btn-primary col-4">Return</a>
                <button class="btn btn-success col-4" type="submit">Save</button>
              </div>
              <input type="hidden" name="cover" value="{{ $item->cover }}">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('javascript')

<script src="{{asset('js/dropzone.min.js')}}" type="text/javascript"></script>
<script>
  // Dropzone.autoDiscover = false;
  function editForm(name, val) {
    var inp = document.querySelector('form#main > input[name="' + name + '"]')
    if (inp)
      inp.setAttribute("value", val);
  }

  var configs = {
    url: "{{ route('upload') }}",
    maxFilesize: 1,
    acceptedFiles: "image/*",
    addRemoveLinks: false,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    maxFiles: 1,
    init: function() {
      this.on("maxfilesexceeded", function(file) {
        this.removeAllFiles();
        this.addFile(file);
      });
    },
    error: function(file, response) {
      console.log('err =>', response);
      return false;
    }
  }

  Dropzone.options.cover = {
    ...configs,
    success: function(file, res) {
      editForm('cover', res.success);
    },
  }
</script>
@endsection

resources/views/dashboard/artists/list.blade.php
@extends('dashboard.base')

@section('content')

<div class="container-fluid">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
        <div class="card">
          <div class="card-header d-flex align-items-center justify-content-between">
            <h4>Artists</h4>
            <a href="{{ route('artists.create') }}" class="btn btn-primary">Add</a>
          </div>
          <div class="card-body">
            <table class="table table-responsive-sm table-striped">
              <thead>
                <tr>
                  <th>Name</th>
                  <th class="text-center">Cover</th>
                  <th class="text-center"># Musics</th>
                  <th class="text-center"># Follow</th>
                  <th class="text-center">Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach($items as $i)
                <tr>
                  <td>
                    <strong>{{ $i->name }}</strong>
                  </td>
                  <td class="text-center" style="height: 85px;">
                    <img src={{ asset("public/"."{$i->cover}") }} height="60" alt="Cover" />
                  </td>
                  <td class="text-center">{{ $i->music_count }}</td>
                  <td class="text-center">{{ $i->follow_count }}</td>
                  <td>
                    <div class="d-flex align-items-center justify-content-around">
                      <a href="{{ url('/artists/' . $i->id . '/edit') }}" class="btn btn-outline-warning" data-toggle="tooltip" title="Edit"><i class="cil-pencil"></i></a>
                      <form action="{{ route('artists.destroy', $i->id ) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-outline-danger" data-toggle="tooltip" title="Delete"><i class="cil-trash"></i></button>
                      </form>
                    </div>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
            {{ $items->links() }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection